import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@shznet/components'

export function HomePage() {
  return (
    <div className='flex flex-1 flex-col gap-4'>
      <div className='space-y-1'>
        <h1 className='text-2xl font-semibold tracking-tight'>Remote Demo</h1>
        <p className='text-sm text-muted-foreground'>
          Minimal module app scaffold generated by @shznet/nx-generators.
        </p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Next step</CardTitle>
          <CardDescription>
            Replace this page with your feature UI and keep shared primitives in @shznet/components or @shznet/core.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <p className='text-sm text-muted-foreground'>
            This module already exposes <code>./Shell</code> and <code>./config</code> for the host.
          </p>
        </CardContent>
      </Card>
    </div>
  )
}
