function buildDashboardPageTsx(options) {
  return `import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '${options.componentsPackage}'
import { Activity, Boxes, CircleDollarSign, ShoppingBag } from 'lucide-react'

const stats = [
  { title: 'Revenue', value: '$28,420', description: '+12.4% vs last week', icon: CircleDollarSign },
  { title: 'Orders', value: '1,204', description: '97 pending review', icon: ShoppingBag },
  { title: 'Products', value: '486', description: '24 low stock alerts', icon: Boxes },
  { title: 'Activity', value: '89%', description: 'SLA within target', icon: Activity },
]

export default function DashboardPage() {
  return (
    <div className='flex flex-1 flex-col gap-4'>
      <div className='flex items-center justify-between'>
        <div>
          <h1 className='text-2xl font-bold tracking-tight'>${options.displayName}</h1>
          <p className='text-sm text-muted-foreground'>Sample dashboard generated by @shz/nx-generators.</p>
        </div>
      </div>

      <div className='grid gap-4 sm:grid-cols-2 xl:grid-cols-4'>
        {stats.map((stat) => (
          <Card key={stat.title}>
            <CardHeader>
              <div className='flex items-center justify-between'>
                <CardDescription>{stat.title}</CardDescription>
                <stat.icon className='size-4 text-muted-foreground' />
              </div>
              <CardTitle className='text-2xl'>{stat.value}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className='text-sm text-muted-foreground'>{stat.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}
`
}

module.exports = { buildDashboardPageTsx }
