import { useEffect, useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle, Skeleton } from '@shznet/components'
import type { ShellHostServices } from '@shznet/core'
import { Activity, Boxes, CircleDollarSign, ShoppingBag } from 'lucide-react'

type DashboardStats = {
  title: string
  value: string
  description: string
  icon: React.ComponentType<{ className?: string }>
}

type HostShellSnapshot = {
  auth?: {
    email: string
    token: string
  } | null
  activeApp?: {
    id: string
    name: string
  }
}

type DashboardPageProps = {
  shellServices?: ShellHostServices
}

async function fetchDashboardStats(): Promise<DashboardStats[]> {
  await new Promise((resolve) => setTimeout(resolve, 500))
  return [
    { title: 'Revenue', value: '$28,420', description: '+12.4% vs last week', icon: CircleDollarSign },
    { title: 'Orders', value: '1,204', description: '97 pending review', icon: ShoppingBag },
    { title: 'Products', value: '486', description: '24 low stock alerts', icon: Boxes },
    { title: 'Activity', value: '89%', description: 'SLA within target', icon: Activity },
  ]
}

function useAsyncData<T>(fetcher: () => Promise<T>) {
  const [data, setData] = useState<T | null>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    let active = true
    fetcher().then((result) => {
      if (!active) return
      setData(result)
      setLoading(false)
    })
    return () => {
      active = false
    }
  }, [])

  return { data, loading }
}

function DashboardSkeleton() {
  return (
    <div className='flex flex-1 flex-col gap-4'>
      <div className='flex items-center justify-between'>
        <div className='space-y-2'>
          <Skeleton className='h-7 w-36' />
          <Skeleton className='h-4 w-72' />
        </div>
      </div>
      <div className='grid gap-4 sm:grid-cols-2 xl:grid-cols-4'>
        {Array.from({ length: 4 }, (_, i) => (
          <Card key={i}>
            <CardHeader>
              <div className='flex items-center justify-between'>
                <Skeleton className='h-4 w-20' />
                <Skeleton className='size-4 rounded' />
              </div>
              <Skeleton className='h-8 w-24 mt-1' />
            </CardHeader>
            <CardContent>
              <Skeleton className='h-4 w-36' />
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}

export default function DashboardPage({ shellServices }: DashboardPageProps) {
  const { data: stats, loading } = useAsyncData(fetchDashboardStats)
  const [token, setToken] = useState<string | null>(null)

  useEffect(() => {
    let active = true
    Promise.resolve(shellServices?.getToken?.() ?? null).then((value) => {
      if (active) setToken(value)
    })
    return () => {
      active = false
    }
  }, [shellServices])

  const shellState = shellServices?.getState?.() as HostShellSnapshot | undefined
  const email = shellState?.auth?.email ?? 'anonymous'
  const activeApp = shellState?.activeApp?.name ?? 'Unknown app'

  if (loading || !stats) return <DashboardSkeleton />

  return (
    <div className='flex flex-1 flex-col gap-4'>
      <div className='flex items-center justify-between'>
        <div>
          <h1 className='text-2xl font-bold tracking-tight'>Admin Sample</h1>
          <p className='text-sm text-muted-foreground'>Sample dashboard generated by @shznet/nx-generators.</p>
        </div>
      </div>

      <div className='grid gap-4 lg:grid-cols-2'>
        <Card>
          <CardHeader>
            <CardTitle className='text-base'>Host bridge</CardTitle>
            <CardDescription>Remote reads host session data through shared services.</CardDescription>
          </CardHeader>
          <CardContent className='space-y-2 text-sm'>
            <p><strong>User:</strong> {email}</p>
            <p><strong>Active app:</strong> {activeApp}</p>
            <p><strong>Token:</strong> {token ?? 'No token from host'}</p>
          </CardContent>
        </Card>
      </div>

      <div className='grid gap-4 sm:grid-cols-2 xl:grid-cols-4'>
        {stats.map((stat) => (
          <Card key={stat.title}>
            <CardHeader>
              <div className='flex items-center justify-between'>
                <CardDescription>{stat.title}</CardDescription>
                <stat.icon className='size-4 text-muted-foreground' />
              </div>
              <CardTitle className='text-2xl'>{stat.value}</CardTitle>
            </CardHeader>
            <CardContent>
              <p className='text-sm text-muted-foreground'>{stat.description}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  )
}
