import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@shznet/components'
import { Link } from 'react-router-dom'
import { apps } from '../../remotes'

export function HomePage() {
  return (
    <div className='mx-auto flex min-h-svh w-full max-w-5xl flex-col gap-6 px-6 py-10'>
      <div className='space-y-2'>
        <h1 className='text-3xl font-semibold tracking-tight'>Demo Host</h1>
        <p className='text-sm text-muted-foreground'>
          Minimal host scaffold generated by @shznet/nx-generators. Add remote entries in src/remotes.ts.
        </p>
      </div>

      {apps.length ? (
        <div className='grid gap-4 md:grid-cols-2'>
          {apps.map((app) => (
            <Link key={app.id} to={app.basePath} className='block'>
              <Card className='h-full transition-colors hover:border-primary/40'>
                <CardHeader>
                  <CardTitle>{app.name}</CardTitle>
                  <CardDescription>{app.basePath}</CardDescription>
                </CardHeader>
                <CardContent>
                  <p className='text-sm text-muted-foreground'>{app.entry}</p>
                </CardContent>
              </Card>
            </Link>
          ))}
        </div>
      ) : (
        <Card>
          <CardHeader>
            <CardTitle>No remotes configured</CardTitle>
            <CardDescription>Update src/remotes.ts with your module definitions.</CardDescription>
          </CardHeader>
        </Card>
      )}
    </div>
  )
}
